version: '3'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./rizzipe_backend
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
